### ISSUE TITLE
Default configuration

### ISSUE THREAD

**Issue by 19h** [bearstech/iptraf-ng#1]
Hey,

first off thanks for iptraf-ng, I love it and use it on all my servers and the Tor exit nodes I operate.

Can I somehow obtain the data produced by the port statistics programmatically via API or at least an ABI?

![bildschirmfoto 2015-11-24 um 17 00 44](https://cloud.githubusercontent.com/assets/280212/11372322/0498afa8-92cd-11e5-8b69-ca8b26deadc8.png)

Thanks!

**_Edit**_ There seems to be a way by using -B and -L with a logfile which would work for now.. maybe I'll look into ripping the logic out of the ncurses

**Comment by zerodeux** [comment]
Sorry, missed that issue ...
We're not the original authors of iptraf-ng, this is a branch where we implemented a beta version of a per-IP statisical breakdown.
I think you want to reach the upstream at https://fedorahosted.org/iptraf-ng/
