### ISSUE TITLE
iptraf-ng contact person

### ISSUE THREAD

**Issue by pecameron** [bearstech/iptraf-ng#2]
Sorry to make contact through a bug. couldn't find another way.

I am working on iptraf-ng for Redhat and I am looking for the upstream project and maintainer. zitune has contributed recently and I am hoping we might discuss what is happening with iptraf-ng
Thanks,
Phil Cameron pcameron@redhat.com

**Comment by gawel** [comment]
This is a fork. See https://github.com/bearstech/iptraf-ng/issues/1#issuecomment-205311657
